[programs.devnet]
myepicproject = "13M5oRdnuywtVknj8RPYC9VhiDfsyLJGrZLwDQEQWtab"

[registry]
url = "https://anchor.projectserum.com"

[provider]
cluster = "devnet"
wallet = "/home/rance/.config/solana/id.json"

[scripts]
test = "node tests/myepicproject.js"
